# Generated by Django 3.2.9 on 2021-11-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('coverImg', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('noOfRoom', models.IntegerField()),
                ('noOfBed', models.IntegerField()),
                ('noOfBath', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('pricePerNight', models.IntegerField()),
                ('aboutHome', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.newuser')),
                ('address', models.CharField(max_length=200)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeIsBooked',
            fields=[
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.home')),
                ('userid', models.IntegerField()),
                ('isBooked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Img2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Img3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Img4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Img5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Img6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Img7', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Img8', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Img9', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Img10', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.home')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.host'),
        ),
    ]
