# Generated by Django 3.2.9 on 2021-12-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211206_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='profile_dp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
