# Generated by Django 3.2.9 on 2021-12-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_newuser_profile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='profile_dp',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
