# Generated by Django 3.2.9 on 2021-12-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_newuser_profile_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimgs',
            name='Img10',
        ),
        migrations.RemoveField(
            model_name='homeimgs',
            name='Img7',
        ),
        migrations.RemoveField(
            model_name='homeimgs',
            name='Img8',
        ),
        migrations.RemoveField(
            model_name='homeimgs',
            name='Img9',
        ),
        migrations.RemoveField(
            model_name='host',
            name='profile_img',
        ),
        migrations.AlterField(
            model_name='home',
            name='coverImg',
            field=models.ImageField(blank=True, null=True, upload_to='assets/uploadedimg'),
        ),
        migrations.AlterField(
            model_name='homeimgs',
            name='Img1',
            field=models.ImageField(blank=True, null=True, upload_to='assets/home_img/'),
        ),
        migrations.AlterField(
            model_name='homeimgs',
            name='Img2',
            field=models.ImageField(blank=True, null=True, upload_to='assets/home_img/'),
        ),
        migrations.AlterField(
            model_name='homeimgs',
            name='Img3',
            field=models.ImageField(blank=True, null=True, upload_to='assets/home_img/'),
        ),
        migrations.AlterField(
            model_name='homeimgs',
            name='Img4',
            field=models.ImageField(blank=True, null=True, upload_to='assets/home_img/'),
        ),
        migrations.AlterField(
            model_name='homeimgs',
            name='Img5',
            field=models.ImageField(blank=True, null=True, upload_to='assets/home_img/'),
        ),
        migrations.AlterField(
            model_name='homeimgs',
            name='Img6',
            field=models.ImageField(blank=True, null=True, upload_to='assets/home_img/'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='profile_dp',
            field=models.ImageField(blank=True, null=True, upload_to='assets/uploadedimg'),
        ),
    ]
