# Generated by Django 3.2.9 on 2021-12-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211206_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='host',
            new_name='host_id',
        ),
    ]
