# Generated by Django 3.2.9 on 2021-12-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_host_home_host_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='host_id',
            new_name='host',
        ),
    ]
