# Generated by Django 3.2.9 on 2021-12-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_host_id_home_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='pricePerNight',
            new_name='pricePerMonth',
        ),
    ]
