# Generated by Django 3.2.9 on 2021-12-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20211222_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='Photofile1',
            new_name='photofile1',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='Photofile2',
            new_name='photofile2',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='Photofile3',
            new_name='photofile3',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='Photofile4',
            new_name='photofile4',
        ),
    ]
