# Generated by Django 3.2.9 on 2022-01-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20211222_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeisbooked',
            name='hostid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
