# Generated by Django 3.2.9 on 2022-01-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='IsHomeApproved',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
